### PR TITLE
Fix key issue

### PR DESCRIPTION
**Pull request by mestre-hugo**
With this you can fix the key console warning in react, related to this [issue](https://github.com/rushik1992/react-hierarchy-chart/issues/2)

### CODE REVIEW

**Review by Nirdosh1024 — APPROVED** [review]
The changes look solid, Thank you for resolving the issue.

**Review by Nirdosh1024 — APPROVED** [review]

**Comment by mestre-hugo** [comment]
You may need to merge this PR for it to go into effect

**Review by Nirdosh1024 — APPROVED** [review]

**Comment by Nirdosh1024** [comment]
> You may need to merge this PR for it to go into effect

Sorry, I don't have any contribution and merging rights.

**Review by svijaykoushik — APPROVED** [review]
Go ahead

**Pull request closed without merging**
